import type { CreatorSkill } from './types'

export const DEFAULT_CREATOR_SKILLS: CreatorSkill[] = [
  {
    id: 'story-continuity',
    name: '故事连续性',
    category: 'story',
    description: '保持人物、剧情、世界观、因果关系一致。',
    systemInstruction: 'Maintain story continuity across all generated text and downstream visual prompts. Preserve characters, world rules, motivations, cause and effect, and timeline coherence.',
    promptInstruction: '延续同一故事设定、人物动机、因果关系和时间线；不要突然改变世界观、角色身份或叙事目标。',
    appliesTo: ['text', 'image', 'video'],
    enabledByDefault: true,
  },
  {
    id: 'visual-style',
    name: '视觉风格',
    category: 'visual',
    description: '统一艺术风格、画面质感、媒介感、时代感。',
    systemInstruction: 'Translate project-level visual style into concrete image and video generation constraints. Keep medium, art direction, production value, and period cues consistent.',
    promptInstruction: '保持统一的艺术风格、画面质感、媒介感、时代符号和制作水准；避免风格漂移。',
    appliesTo: ['image', 'video'],
    enabledByDefault: true,
  },
  {
    id: 'color-grading',
    name: '色彩/调色',
    category: 'color',
    description: '统一主色调、光影、对比度、饱和度、氛围。',
    systemInstruction: 'Apply consistent color grading, lighting contrast, saturation, mood, and palette decisions to visual outputs.',
    promptInstruction: '统一主色调、光影方向、对比度、饱和度和氛围；不要引入冲突的调色方案。',
    appliesTo: ['image', 'video'],
    enabledByDefault: true,
  },
  {
    id: 'camera-language',
    name: '镜头语言',
    category: 'camera',
    description: '统一景别、焦段、构图、运动方式、摄影风格。',
    systemInstruction: 'Use a coherent camera language: shot size, lens, angle, composition, motion, depth of field, and cinematic framing.',
    promptInstruction: '明确景别、焦段、机位、构图、镜头运动和摄影风格，并保持连续镜头语言。',
    appliesTo: ['image', 'video'],
    enabledByDefault: true,
  },
  {
    id: 'character-scene-consistency',
    name: '人物/场景一致性',
    category: 'character',
    description: '保持人物外貌、服装、道具、场景结构连续。',
    systemInstruction: 'Preserve character appearance, wardrobe, props, scene layout, architecture, weather, and spatial continuity across text, image, and video.',
    promptInstruction: '保持人物外貌、服装、道具、场景结构、天气和空间关系一致；不要改变角色年龄、身份或核心场景结构。',
    appliesTo: ['text', 'image', 'video'],
    enabledByDefault: true,
  },
]
