export type ToolProviderCategory =
  | 'image-to-video'
  | 'text-to-script'
  | 'text-to-image'
  | 'voice'
  | 'dubbing'
  | 'audio-cleanup'
  | 'music-ost'
  | 'video'
  | 'agent'
  | 'skill'

export type ToolProviderType = 'model' | 'app' | 'api' | 'bridge' | 'workflow'
export type ToolProviderStatus = 'available' | 'mock' | 'bridge-only' | 'not-configured' | 'coming-soon' | 'error'
export type ToolProviderTestMode = 'real' | 'mock' | 'unavailable'
export type ToolProviderInput = 'text' | 'image' | 'video' | 'audio' | 'file'
export type ToolProviderOutput = 'text' | 'image' | 'video' | 'audio' | 'music' | 'script' | 'storyboard' | 'voice'
export type ToolProviderRecommendation =
  | 'canvas-text'
  | 'canvas-image'
  | 'canvas-video'
  | 'canvas-audio'
  | 'script'
  | 'voice'
  | 'ost'
  | 'delivery'

export interface ToolProvider {
  id: string
  name: string
  displayName: string
  aliases?: string[]
  category: ToolProviderCategory
  providerType: ToolProviderType
  status: ToolProviderStatus
  versionLabel?: string
  description: string
  useCases: string[]
  supportedInputs: ToolProviderInput[]
  supportedOutputs: ToolProviderOutput[]
  canTest: boolean
  testMode: ToolProviderTestMode
  setupHint: string
  sourcePath: string
  tags: string[]
  recommendedFor: ToolProviderRecommendation[]
}

export const PROVIDER_CATEGORY_LABELS: Record<ToolProviderCategory, string> = {
  'image-to-video': '图生视频',
  'text-to-script': '文生剧本',
  'text-to-image': '文生图',
  voice: '配音 / 声音',
  dubbing: '配音 / 声音',
  'audio-cleanup': '配音 / 声音',
  'music-ost': 'OST / 音乐',
  video: '视频',
  agent: 'Agents',
  skill: 'Skills',
}

export const PROVIDER_CATEGORY_ORDER: ToolProviderCategory[] = [
  'image-to-video',
  'text-to-script',
  'text-to-image',
  'voice',
  'dubbing',
  'audio-cleanup',
  'music-ost',
  'agent',
  'skill',
]

export const TOOL_PROVIDERS: ToolProvider[] = [
  {
    id: 'chatgpt-image-video',
    name: 'chatgpt',
    displayName: 'ChatGPT',
    category: 'image-to-video',
    providerType: 'model',
    status: 'not-configured',
    description: '作为图生视频创作入口登记；当前没有可确认的视频 adapter、endpoint 或 key。',
    useCases: ['首帧续写', '镜头动效描述', '视频 prompt 起草'],
    supportedInputs: ['image', 'text'],
    supportedOutputs: ['video'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '未配置真实视频生成 endpoint；Canvas 只能作为模拟选择。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['image-to-video', 'openai'],
    recommendedFor: ['canvas-video'],
  },
  {
    id: 'seedance',
    name: 'seedance',
    displayName: 'Seedance',
    aliases: ['see dance'],
    category: 'image-to-video',
    providerType: 'model',
    status: 'not-configured',
    description: '图生视频 provider 目录项；当前前端没有真实调用链路。',
    useCases: ['首帧生成视频', '镜头运动', '短片动态化'],
    supportedInputs: ['image', 'text'],
    supportedOutputs: ['video'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '需要补齐 adapter、endpoint 和 API key 后才能真实测试。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['image-to-video'],
    recommendedFor: ['canvas-video'],
  },
  {
    id: 'gemini-video',
    name: 'gemini',
    displayName: 'Gemini',
    category: 'image-to-video',
    providerType: 'model',
    status: 'not-configured',
    description: '登记为图生视频候选模型；当前没有真实视频 adapter。',
    useCases: ['图像理解', '镜头 prompt', '视频生成选择'],
    supportedInputs: ['image', 'text'],
    supportedOutputs: ['video'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '未配置 Google provider key 或视频生成 endpoint。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['google', 'image-to-video'],
    recommendedFor: ['canvas-video'],
  },
  {
    id: 'vidu',
    name: 'vidu',
    displayName: 'Vidu',
    category: 'image-to-video',
    providerType: 'model',
    status: 'not-configured',
    description: '图生视频候选 provider；平台内尚未接通真实执行。',
    useCases: ['参考图转视频', '角色动作', '短镜头生成'],
    supportedInputs: ['image', 'text'],
    supportedOutputs: ['video'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '需要新增 adapter 和密钥配置。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['image-to-video'],
    recommendedFor: ['canvas-video'],
  },
  {
    id: 'runway',
    name: 'runway',
    displayName: 'Runway',
    category: 'image-to-video',
    providerType: 'app',
    status: 'mock',
    description: 'Canvas 已把 Runway 作为视频节点默认选择之一，但当前只是前端模拟生成。',
    useCases: ['视频节点占位', '镜头运动', '创作流程验证'],
    supportedInputs: ['image', 'text'],
    supportedOutputs: ['video'],
    canTest: true,
    testMode: 'mock',
    setupHint: '没有真实 Runway API 调用；生成结果为前端 mock。',
    sourcePath: 'apps/web/src/components/create/VisualCanvasWorkspace.tsx',
    tags: ['canvas', 'mock', 'image-to-video'],
    recommendedFor: ['canvas-video'],
  },
  {
    id: 'sora',
    name: 'sora',
    displayName: 'OpenAI Sora',
    aliases: ['Sora 2', 'OpenAI Sora / Sora 2'],
    category: 'image-to-video',
    providerType: 'model',
    status: 'not-configured',
    versionLabel: 'Sora 2',
    description: '作为视频生成候选登记；当前没有 Sora adapter 或可调用 endpoint。',
    useCases: ['图生视频', '文本辅助视频生成', '镜头创作'],
    supportedInputs: ['image', 'text'],
    supportedOutputs: ['video'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '未配置真实 OpenAI 视频生成链路。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['openai', 'sora', 'image-to-video'],
    recommendedFor: ['canvas-video'],
  },
  {
    id: 'kling',
    name: 'kling',
    displayName: 'Kling AI',
    aliases: ['可灵'],
    category: 'image-to-video',
    providerType: 'model',
    status: 'mock',
    description: 'Canvas 已把 Kling 作为视频节点可选模型；当前只用于模拟工作流。',
    useCases: ['首帧转视频', '动作生成', '视频节点占位'],
    supportedInputs: ['image', 'text'],
    supportedOutputs: ['video'],
    canTest: true,
    testMode: 'mock',
    setupHint: '没有真实 Kling API 调用；只做 mock 选择。',
    sourcePath: 'apps/web/src/components/create/CanvasNodeCard.tsx',
    tags: ['canvas', 'mock', 'image-to-video'],
    recommendedFor: ['canvas-video'],
  },
  {
    id: 'google-veo',
    name: 'google-veo',
    displayName: 'Google Veo',
    aliases: ['Google Veo 3.1'],
    category: 'image-to-video',
    providerType: 'model',
    status: 'not-configured',
    versionLabel: '3.1',
    description: '图生视频候选 provider；当前未接入真实 Google Veo 调用。',
    useCases: ['高质量视频生成', '参考图动态化', '镜头生成'],
    supportedInputs: ['image', 'text'],
    supportedOutputs: ['video'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '未配置 Google Veo endpoint 或密钥。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['google', 'veo', 'image-to-video'],
    recommendedFor: ['canvas-video'],
  },
  {
    id: 'luma-dream-machine',
    name: 'luma-dream-machine',
    displayName: 'Luma Dream Machine',
    aliases: ['Ray 3.14'],
    category: 'image-to-video',
    providerType: 'model',
    status: 'not-configured',
    versionLabel: 'Ray 3.14',
    description: '登记为图生视频候选；当前没有真实 Luma adapter。',
    useCases: ['图像动态化', '镜头生成', '视觉预演'],
    supportedInputs: ['image', 'text'],
    supportedOutputs: ['video'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '需要真实 adapter、endpoint 与 key。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['luma', 'image-to-video'],
    recommendedFor: ['canvas-video'],
  },
  {
    id: 'pika',
    name: 'pika',
    displayName: 'Pika',
    aliases: ['Pika 2.0'],
    category: 'image-to-video',
    providerType: 'model',
    status: 'not-configured',
    versionLabel: '2.0',
    description: '图生视频候选 provider；当前未接通真实 API。',
    useCases: ['短视频生成', '首帧续写', '风格化动态'],
    supportedInputs: ['image', 'text'],
    supportedOutputs: ['video'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '没有 adapter 或平台密钥配置。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['image-to-video'],
    recommendedFor: ['canvas-video'],
  },
  {
    id: 'happyhorse',
    name: 'happyhorse',
    displayName: 'happyhorse',
    category: 'image-to-video',
    providerType: 'app',
    status: 'not-configured',
    description: '按目录要求登记为图生视频工具；当前没有可验证接入。',
    useCases: ['图生视频候选', '外部工具评估'],
    supportedInputs: ['image', 'text'],
    supportedOutputs: ['video'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '未配置 endpoint、key 或 adapter。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['image-to-video'],
    recommendedFor: ['canvas-video'],
  },
  {
    id: 'anthropic-claude',
    name: 'claude',
    displayName: 'Claude',
    aliases: ['Claude 4.7', 'Anthropic'],
    category: 'text-to-script',
    providerType: 'model',
    status: 'mock',
    versionLabel: '4.7',
    description: 'Canvas 文本节点已有 Claude 选项；没有确认真实 Anthropic key，当前按 mock 处理。',
    useCases: ['剧本起稿', '角色对话', 'storyboard 文案'],
    supportedInputs: ['text'],
    supportedOutputs: ['script', 'storyboard', 'text'],
    canTest: true,
    testMode: 'mock',
    setupHint: '没有真实 Anthropic API 配置；只作为模拟模型选择。',
    sourcePath: 'apps/web/src/components/create/CanvasNodeCard.tsx',
    tags: ['script', 'mock'],
    recommendedFor: ['script', 'canvas-text'],
  },
  {
    id: 'deepseek',
    name: 'deepseek',
    displayName: 'DeepSeek',
    category: 'text-to-script',
    providerType: 'model',
    status: 'not-configured',
    description: '文生剧本候选 provider；当前没有 adapter 或 key。',
    useCases: ['长文本剧本', '结构拆解', '对白改写'],
    supportedInputs: ['text'],
    supportedOutputs: ['script', 'storyboard', 'text'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '需要配置 DeepSeek endpoint 和 API key。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['script'],
    recommendedFor: ['script', 'canvas-text'],
  },
  {
    id: 'doubao',
    name: 'doubao',
    displayName: '豆包',
    category: 'text-to-script',
    providerType: 'model',
    status: 'not-configured',
    description: '文生剧本候选 provider；当前未接入真实调用。',
    useCases: ['中文剧本', '文案生成', '创意扩写'],
    supportedInputs: ['text'],
    supportedOutputs: ['script', 'storyboard', 'text'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '需要补齐 adapter、endpoint 与密钥。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['script', 'chinese'],
    recommendedFor: ['script', 'canvas-text'],
  },
  {
    id: 'openai-gpt-5',
    name: 'gpt-5',
    displayName: 'GPT-5',
    aliases: ['OpenAI'],
    category: 'text-to-script',
    providerType: 'model',
    status: 'not-configured',
    versionLabel: 'GPT-5',
    description: '文生剧本候选 provider；当前没有在前端确认真实 OpenAI 文本生成链路。',
    useCases: ['剧本起稿', '分镜描述', '创意扩写'],
    supportedInputs: ['text'],
    supportedOutputs: ['script', 'storyboard', 'text'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '需要真实 OpenAI adapter 和环境变量后才可标记 available。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['openai', 'script'],
    recommendedFor: ['script', 'canvas-text'],
  },
  {
    id: 'squibler',
    name: 'squibler',
    displayName: '斯奎布勒',
    aliases: ['Squibler'],
    category: 'text-to-script',
    providerType: 'app',
    status: 'not-configured',
    description: '剧本写作工具目录项；当前未桥接或接 API。',
    useCases: ['剧本写作', '故事扩写', '大纲整理'],
    supportedInputs: ['text'],
    supportedOutputs: ['script', 'storyboard', 'text'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '未配置外部工具连接。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['script', 'app'],
    recommendedFor: ['script', 'canvas-text'],
  },
  {
    id: 'arc-studio',
    name: 'arc-studio',
    displayName: 'Arc Studio',
    category: 'text-to-script',
    providerType: 'app',
    status: 'not-configured',
    description: '专业剧本工具目录项；当前没有导入导出桥接实现。',
    useCases: ['剧本编辑', '格式化 screenplay', '创作管理'],
    supportedInputs: ['text'],
    supportedOutputs: ['script', 'storyboard', 'text'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '需要桥接格式或 API 才能执行。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['script', 'app'],
    recommendedFor: ['script', 'canvas-text'],
  },
  {
    id: 'sudowrite',
    name: 'sudowrite',
    displayName: 'Sudowrite',
    category: 'text-to-script',
    providerType: 'app',
    status: 'not-configured',
    description: '创意写作工具目录项；当前未接入真实 API。',
    useCases: ['故事扩写', '语气改写', '创意段落'],
    supportedInputs: ['text'],
    supportedOutputs: ['script', 'storyboard', 'text'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '未配置可调用 endpoint。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['script', 'app'],
    recommendedFor: ['script', 'canvas-text'],
  },
  {
    id: 'nano-banana',
    name: 'nano-banana',
    displayName: 'nano banana',
    category: 'text-to-image',
    providerType: 'model',
    status: 'mock',
    description: 'Canvas 图片节点已有该选项；当前仅模拟图片生成流程。',
    useCases: ['关键画面', '风格探索', '背景替换占位'],
    supportedInputs: ['text', 'image'],
    supportedOutputs: ['image'],
    canTest: true,
    testMode: 'mock',
    setupHint: '没有真实图片 API 调用；只做前端 mock。',
    sourcePath: 'apps/web/src/components/create/VisualCanvasWorkspace.tsx',
    tags: ['image', 'mock'],
    recommendedFor: ['canvas-image'],
  },
  {
    id: 'openai-gpt-images',
    name: 'openai-gpt-images',
    displayName: 'OpenAI GPT Images',
    aliases: ['OpenAI GPT Images 2.0'],
    category: 'text-to-image',
    providerType: 'model',
    status: 'not-configured',
    versionLabel: '2.0',
    description: '文生图候选 provider；当前没有真实 image adapter 或 endpoint。',
    useCases: ['文生图', '图片编辑', '关键视觉'],
    supportedInputs: ['text', 'image'],
    supportedOutputs: ['image'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '需要真实 OpenAI image endpoint 与 key。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['openai', 'image'],
    recommendedFor: ['canvas-image'],
  },
  {
    id: 'flux-pro',
    name: 'flux-pro',
    displayName: 'Flux Pro',
    aliases: ['Flux 2 Pro', '黑森林实验室'],
    category: 'text-to-image',
    providerType: 'model',
    status: 'not-configured',
    versionLabel: '2 Pro',
    description: '文生图候选 provider；当前未配置真实调用。',
    useCases: ['风格概念图', '关键帧', '角色设定'],
    supportedInputs: ['text', 'image'],
    supportedOutputs: ['image'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '需要 adapter、endpoint 与 key。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['image', 'black-forest-labs'],
    recommendedFor: ['canvas-image'],
  },
  {
    id: 'midjourney',
    name: 'midjourney',
    displayName: 'Midjourney',
    aliases: ['Midjourney V7', '中途 V7'],
    category: 'text-to-image',
    providerType: 'app',
    status: 'not-configured',
    versionLabel: 'V7',
    description: '文生图工具目录项；当前没有官方可用 API 链路，不能标为 available。',
    useCases: ['概念图', '风格参考', '角色视觉'],
    supportedInputs: ['text', 'image'],
    supportedOutputs: ['image'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '未配置可验证 API；只作为目录候选显示。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['image', 'app'],
    recommendedFor: ['canvas-image'],
  },
  {
    id: 'adobe-firefly',
    name: 'adobe-firefly',
    displayName: 'Adobe Firefly',
    aliases: ['Adobe Firefly 4'],
    category: 'text-to-image',
    providerType: 'api',
    status: 'not-configured',
    versionLabel: '4',
    description: '文生图候选 provider；当前没有平台内真实 adapter。',
    useCases: ['商业视觉', '素材生成', '图片编辑'],
    supportedInputs: ['text', 'image'],
    supportedOutputs: ['image'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '需要 Firefly API 配置后才能真实测试。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['adobe', 'image'],
    recommendedFor: ['canvas-image'],
  },
  {
    id: 'recraft',
    name: 'recraft',
    displayName: 'Recraft',
    aliases: ['Recraft V3'],
    category: 'text-to-image',
    providerType: 'api',
    status: 'not-configured',
    versionLabel: 'V3',
    description: '文生图候选 provider；当前未接入真实 API。',
    useCases: ['品牌视觉', '插画', '图像生成'],
    supportedInputs: ['text', 'image'],
    supportedOutputs: ['image'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '需要 adapter 与 key。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['image'],
    recommendedFor: ['canvas-image'],
  },
  {
    id: 'ideogram',
    name: 'ideogram',
    displayName: '象形文字',
    aliases: ['象形文字 V3', 'Ideogram V3'],
    category: 'text-to-image',
    providerType: 'model',
    status: 'not-configured',
    versionLabel: 'V3',
    description: '文生图候选 provider；当前没有真实调用链路。',
    useCases: ['带字海报', '品牌视觉', '概念图'],
    supportedInputs: ['text', 'image'],
    supportedOutputs: ['image'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '未配置 endpoint 或 key。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['image', 'typography'],
    recommendedFor: ['canvas-image'],
  },
  {
    id: 'elevenlabs',
    name: 'elevenlabs',
    displayName: 'ElevenLabs',
    aliases: ['ElevenLabs V3 Turbo'],
    category: 'voice',
    providerType: 'api',
    status: 'not-configured',
    versionLabel: 'V3 Turbo',
    description: '仓库有 adapter 注册，但没有确认 API key 或真实执行链路。',
    useCases: ['旁白生成', '角色声音', '配音测试'],
    supportedInputs: ['text', 'audio'],
    supportedOutputs: ['audio', 'voice'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '需要 API key 与执行 endpoint；当前不能标记 available。',
    sourcePath: 'apps/web/src/lib/adapters/registry.ts',
    tags: ['voice', 'adapter'],
    recommendedFor: ['canvas-audio', 'voice', 'delivery'],
  },
  {
    id: 'resemble-ai',
    name: 'resemble-ai',
    displayName: 'Resemble AI',
    category: 'voice',
    providerType: 'api',
    status: 'not-configured',
    description: '声音生成候选 provider；当前未接入真实 API。',
    useCases: ['声音克隆', '角色配音', '旁白'],
    supportedInputs: ['text', 'audio'],
    supportedOutputs: ['audio', 'voice'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '需要 endpoint 与 key。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['voice'],
    recommendedFor: ['canvas-audio', 'voice', 'delivery'],
  },
  {
    id: 'azure-ai-speech',
    name: 'azure-ai-speech',
    displayName: 'Microsoft Azure AI Speech',
    aliases: ['Microsoft Azure AI Speech 2026 Edition'],
    category: 'voice',
    providerType: 'api',
    status: 'not-configured',
    versionLabel: '2026 Edition',
    description: '语音 provider 目录项；当前没有环境配置证明可用。',
    useCases: ['TTS', '语音识别', '旁白'],
    supportedInputs: ['text', 'audio'],
    supportedOutputs: ['audio', 'voice'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '需要 Azure Speech key、region 和 adapter。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['microsoft', 'voice'],
    recommendedFor: ['canvas-audio', 'voice', 'delivery'],
  },
  {
    id: 'heygen',
    name: 'heygen',
    displayName: 'HeyGen',
    aliases: ['HeyGen Video Translate 3.0', 'HeyGen Video Translate'],
    category: 'dubbing',
    providerType: 'api',
    status: 'not-configured',
    versionLabel: 'Video Translate 3.0',
    description: '去重后的 HeyGen provider，覆盖普通 HeyGen 与 Video Translate 名称；当前未接入真实 API。',
    useCases: ['视频翻译', '配音', '口型同步'],
    supportedInputs: ['text', 'audio', 'video'],
    supportedOutputs: ['audio', 'voice', 'video'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '需要 HeyGen adapter、endpoint 与 key。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['dubbing', 'video-translate', 'deduped'],
    recommendedFor: ['canvas-audio', 'voice', 'delivery'],
  },
  {
    id: 'rask-ai',
    name: 'rask-ai',
    displayName: 'Rask AI',
    category: 'dubbing',
    providerType: 'api',
    status: 'not-configured',
    description: '视频翻译和配音候选 provider；当前未接入。',
    useCases: ['视频翻译', '多语言配音', '本地化'],
    supportedInputs: ['text', 'audio', 'video'],
    supportedOutputs: ['audio', 'voice', 'video'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '未配置 API 连接。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['dubbing'],
    recommendedFor: ['canvas-audio', 'voice', 'delivery'],
  },
  {
    id: 'dubverse',
    name: 'dubverse',
    displayName: 'Dubverse',
    category: 'dubbing',
    providerType: 'api',
    status: 'not-configured',
    description: '配音和视频本地化目录项；当前没有真实 adapter。',
    useCases: ['多语言配音', '字幕配音', '交付本地化'],
    supportedInputs: ['text', 'audio', 'video'],
    supportedOutputs: ['audio', 'voice', 'video'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '需要 endpoint、key 和导入导出映射。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['dubbing'],
    recommendedFor: ['canvas-audio', 'voice', 'delivery'],
  },
  {
    id: 'adobe-podcast-enhance',
    name: 'adobe-podcast-enhance',
    displayName: 'Adobe Podcast Enhance Speech',
    category: 'audio-cleanup',
    providerType: 'app',
    status: 'not-configured',
    description: '音频清理候选工具；当前未接入真实处理。',
    useCases: ['降噪', '人声增强', '采访音频清理'],
    supportedInputs: ['audio', 'video'],
    supportedOutputs: ['audio', 'voice'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '没有可执行 API 或桥接格式。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['audio-cleanup', 'adobe'],
    recommendedFor: ['canvas-audio', 'voice', 'delivery'],
  },
  {
    id: 'izotope-rx',
    name: 'izotope-rx',
    displayName: 'iZotope RX',
    aliases: ['iZotope RX 12 AI Assist'],
    category: 'audio-cleanup',
    providerType: 'app',
    status: 'not-configured',
    versionLabel: 'RX 12 AI Assist',
    description: '音频修复工具目录项；当前没有插件桥接或 API。',
    useCases: ['降噪', '修复', '后期声音清理'],
    supportedInputs: ['audio', 'video'],
    supportedOutputs: ['audio', 'voice'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '需要桥接流程后才可执行。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['audio-cleanup'],
    recommendedFor: ['canvas-audio', 'voice', 'delivery'],
  },
  {
    id: 'lalal-ai',
    name: 'lalal-ai',
    displayName: 'LALAL.AI',
    category: 'audio-cleanup',
    providerType: 'api',
    status: 'not-configured',
    description: '音频分离候选 provider；当前未接通真实 API。',
    useCases: ['人声分离', '伴奏分离', '音频清理'],
    supportedInputs: ['audio', 'video'],
    supportedOutputs: ['audio', 'voice'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '需要 API key 和 adapter。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['audio-cleanup'],
    recommendedFor: ['canvas-audio', 'voice', 'delivery'],
  },
  {
    id: 'voice-ai',
    name: 'voice-ai',
    displayName: 'Voice.ai',
    category: 'voice',
    providerType: 'app',
    status: 'not-configured',
    description: '语音转换候选工具；当前未接入真实调用。',
    useCases: ['变声', '角色声音', '声音实验'],
    supportedInputs: ['text', 'audio'],
    supportedOutputs: ['audio', 'voice'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '没有 adapter 或 bridge。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['voice'],
    recommendedFor: ['canvas-audio', 'voice', 'delivery'],
  },
  {
    id: 'udio',
    name: 'udio',
    displayName: 'Udio',
    aliases: ['Udio V2.5'],
    category: 'music-ost',
    providerType: 'model',
    status: 'not-configured',
    versionLabel: 'V2.5',
    description: '去重后的 Udio 音乐 provider；当前未接入真实 API。',
    useCases: ['OST 草稿', '主题曲', '情绪音乐'],
    supportedInputs: ['text'],
    supportedOutputs: ['music', 'audio'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '没有可验证 adapter、endpoint 或 key。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['music', 'ost', 'deduped'],
    recommendedFor: ['ost', 'canvas-audio'],
  },
  {
    id: 'suno',
    name: 'suno',
    displayName: 'Suno',
    aliases: ['Suno V4.5'],
    category: 'music-ost',
    providerType: 'model',
    status: 'not-configured',
    versionLabel: 'V4.5',
    description: '去重后的 Suno 音乐 provider；当前未接入真实调用。',
    useCases: ['歌曲草稿', 'OST', '情绪音乐'],
    supportedInputs: ['text'],
    supportedOutputs: ['music', 'audio'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '未配置可用 API。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['music', 'ost', 'deduped'],
    recommendedFor: ['ost', 'canvas-audio'],
  },
  {
    id: 'aiva',
    name: 'aiva',
    displayName: 'AIVA',
    category: 'music-ost',
    providerType: 'app',
    status: 'not-configured',
    description: 'OST 与配乐候选 provider；当前无真实接入。',
    useCases: ['配乐', '主题音乐', '情绪段落'],
    supportedInputs: ['text'],
    supportedOutputs: ['music', 'audio'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '需要 API 或桥接格式。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['music', 'ost'],
    recommendedFor: ['ost', 'canvas-audio'],
  },
  {
    id: 'stable-audio',
    name: 'stable-audio',
    displayName: 'Stable Audio',
    aliases: ['Stable Audio 3.0', 'Stability AI'],
    category: 'music-ost',
    providerType: 'model',
    status: 'not-configured',
    versionLabel: '3.0',
    description: '去重后的 Stable Audio provider；当前没有真实 Stability adapter。',
    useCases: ['音乐生成', '音效', 'OST 草稿'],
    supportedInputs: ['text'],
    supportedOutputs: ['music', 'audio'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '需要 Stability API 配置。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['music', 'ost', 'deduped'],
    recommendedFor: ['ost', 'canvas-audio'],
  },
  {
    id: 'google-music',
    name: 'google-music',
    displayName: 'Google Music',
    aliases: ['Google MusicLM', 'Lyria 3'],
    category: 'music-ost',
    providerType: 'model',
    status: 'not-configured',
    versionLabel: 'Lyria 3',
    description: 'Google 音乐生成目录项；MusicLM / Lyria 合并为同一 provider 显示。',
    useCases: ['音乐生成', 'OST', '主题动机'],
    supportedInputs: ['text'],
    supportedOutputs: ['music', 'audio'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '未配置 Google 音乐生成 endpoint 或 key。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['google', 'music', 'ost', 'deduped'],
    recommendedFor: ['ost', 'canvas-audio'],
  },
  {
    id: 'soniqs',
    name: 'soniqs',
    displayName: 'Soniqs',
    category: 'music-ost',
    providerType: 'app',
    status: 'not-configured',
    description: '音乐生成候选工具；当前未接入真实 API。',
    useCases: ['音乐草稿', '氛围音乐', 'OST 参考'],
    supportedInputs: ['text'],
    supportedOutputs: ['music', 'audio'],
    canTest: false,
    testMode: 'unavailable',
    setupHint: '未配置 adapter 或 key。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['music', 'ost'],
    recommendedFor: ['ost', 'canvas-audio'],
  },
  {
    id: 'ai-director-agent',
    name: 'ai-director-agent',
    displayName: 'AI Director Agent',
    category: 'agent',
    providerType: 'workflow',
    status: 'mock',
    description: 'Agent 状态展示项；没有确认真实多 agent 执行链路。',
    useCases: ['导演视角', '创作统筹', '镜头方向'],
    supportedInputs: ['text', 'image', 'file'],
    supportedOutputs: ['text', 'script', 'storyboard'],
    canTest: true,
    testMode: 'mock',
    setupHint: '只做状态中心与 Canvas 模拟入口，不标记真实可用。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['agent', 'mock'],
    recommendedFor: ['canvas-text', 'script'],
  },
  {
    id: 'cinematographer-agent',
    name: 'cinematographer-agent',
    displayName: 'Cinematographer Agent',
    category: 'agent',
    providerType: 'workflow',
    status: 'mock',
    description: '摄影 agent 展示项；当前没有真实运行链路。',
    useCases: ['摄影建议', '景别', '机位'],
    supportedInputs: ['text', 'image'],
    supportedOutputs: ['text', 'storyboard'],
    canTest: true,
    testMode: 'mock',
    setupHint: '仅模拟，不触发真实 provider。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['agent', 'mock'],
    recommendedFor: ['canvas-text', 'script'],
  },
  {
    id: 'editor-agent',
    name: 'editor-agent',
    displayName: 'Editor Agent',
    category: 'agent',
    providerType: 'workflow',
    status: 'mock',
    description: '剪辑 agent 展示项；当前只用于目录状态。',
    useCases: ['剪辑节奏', '结构收束', '版本建议'],
    supportedInputs: ['text', 'video', 'file'],
    supportedOutputs: ['text', 'storyboard'],
    canTest: true,
    testMode: 'mock',
    setupHint: '没有真实 agent runner，按 mock 展示。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['agent', 'mock'],
    recommendedFor: ['canvas-text', 'delivery'],
  },
  {
    id: 'sound-agent',
    name: 'sound-agent',
    displayName: 'Sound Agent',
    category: 'agent',
    providerType: 'workflow',
    status: 'mock',
    description: '声音 agent 展示项；当前只模拟声音方向建议。',
    useCases: ['声音设计', '配乐建议', '旁白方向'],
    supportedInputs: ['text', 'audio', 'video'],
    supportedOutputs: ['text', 'audio', 'music'],
    canTest: true,
    testMode: 'mock',
    setupHint: '没有真实运行链路。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['agent', 'mock'],
    recommendedFor: ['canvas-audio', 'voice', 'ost'],
  },
  {
    id: 'delivery-agent',
    name: 'delivery-agent',
    displayName: 'Delivery Agent',
    category: 'agent',
    providerType: 'workflow',
    status: 'mock',
    description: '交付 agent 展示项；当前不执行真实导出。',
    useCases: ['交付摘要', '版本检查', '客户包说明'],
    supportedInputs: ['text', 'video', 'audio', 'file'],
    supportedOutputs: ['text'],
    canTest: true,
    testMode: 'mock',
    setupHint: '只做状态展示和 mock 反馈。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['agent', 'mock'],
    recommendedFor: ['delivery'],
  },
  {
    id: 'script-skill',
    name: 'script-skill',
    displayName: 'Script Skill',
    category: 'skill',
    providerType: 'workflow',
    status: 'mock',
    description: 'Skill 状态展示项；不修改 skills 底层，不标记真实可用。',
    useCases: ['剧本生成', '文案结构', '改写'],
    supportedInputs: ['text'],
    supportedOutputs: ['script', 'text'],
    canTest: true,
    testMode: 'mock',
    setupHint: '当前只展示 skill 能力状态，依赖模型仍按 mock 处理。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['skill', 'mock'],
    recommendedFor: ['script', 'canvas-text'],
  },
  {
    id: 'storyboard-skill',
    name: 'storyboard-skill',
    displayName: 'Storyboard Skill',
    category: 'skill',
    providerType: 'workflow',
    status: 'mock',
    description: '分镜 skill 展示项；当前不触发真实底层 skill 逻辑。',
    useCases: ['分镜', '镜头拆解', 'storyboard'],
    supportedInputs: ['text', 'image'],
    supportedOutputs: ['storyboard', 'text'],
    canTest: true,
    testMode: 'mock',
    setupHint: '只做状态中心 mock 展示。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['skill', 'mock'],
    recommendedFor: ['script', 'canvas-text'],
  },
  {
    id: 'review-skill',
    name: 'review-skill',
    displayName: 'Review Skill',
    category: 'skill',
    providerType: 'workflow',
    status: 'mock',
    description: '审片 skill 展示项；当前没有真实评审执行链路。',
    useCases: ['审片意见', '修改建议', '质量检查'],
    supportedInputs: ['text', 'video', 'file'],
    supportedOutputs: ['text'],
    canTest: true,
    testMode: 'mock',
    setupHint: '仅展示状态和模拟反馈。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['skill', 'mock'],
    recommendedFor: ['delivery'],
  },
  {
    id: 'delivery-skill',
    name: 'delivery-skill',
    displayName: 'Delivery Skill',
    category: 'skill',
    providerType: 'workflow',
    status: 'mock',
    description: '交付 skill 展示项；当前不做真实交付导出。',
    useCases: ['交付清单', '版本摘要', '客户包说明'],
    supportedInputs: ['text', 'video', 'audio', 'file'],
    supportedOutputs: ['text'],
    canTest: true,
    testMode: 'mock',
    setupHint: '没有真实导出执行，只做 mock 状态。',
    sourcePath: 'apps/web/src/lib/tools/provider-catalog.ts',
    tags: ['skill', 'mock'],
    recommendedFor: ['delivery'],
  },
]

export function getAllToolProviders() {
  return TOOL_PROVIDERS
}

export function getToolProviderById(id: string) {
  return TOOL_PROVIDERS.find((provider) => provider.id === id) ?? null
}

export function getToolProvidersByCategory(category: ToolProviderCategory) {
  return TOOL_PROVIDERS.filter((provider) => provider.category === category)
}

export function getToolProvidersForRecommendation(recommendation: ToolProviderRecommendation) {
  return TOOL_PROVIDERS.filter((provider) => provider.recommendedFor.includes(recommendation))
}
