import type { OpenSourceToolDefinition } from './types'

export const OPEN_SOURCE_TOOL_REGISTRY: OpenSourceToolDefinition[] = [
  // ── P0: Core infrastructure ──────────────────────────────────────────────
  {
    id: 'supabase-storage',
    name: 'Supabase Storage',
    tier: 'P0',
    category: 'storage',
    description: 'S3-compatible object storage for user assets and generated media.',
    license: 'Apache-2.0',
    risk: 'safe',
    featureFlag: 'NEXT_PUBLIC_ENABLE_SUPABASE_STORAGE',
    envKeys: ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY', 'NEXT_PUBLIC_SUPABASE_URL'],
    productSurface: ['asset-upload', 'media-persistence', 'project-assets'],
    userVisibleCapability: '云端媒体存储',
    stars: 72000,
    homepage: 'https://supabase.com/storage',
  },
  {
    id: 'bullmq',
    name: 'BullMQ',
    tier: 'P0',
    category: 'queue',
    description: 'Redis-backed job queue for async video generation and media processing tasks.',
    license: 'MIT',
    risk: 'safe',
    featureFlag: 'NEXT_PUBLIC_ENABLE_BULLMQ',
    envKeys: ['REDIS_URL', 'REDIS_HOST', 'REDIS_PORT'],
    productSurface: ['video-generation', 'async-jobs', 'media-processing'],
    userVisibleCapability: '异步任务队列',
    stars: 6200,
    homepage: 'https://bullmq.io',
  },
  {
    id: 'react-flow',
    name: 'React Flow',
    tier: 'P0',
    category: 'canvas',
    description: 'Node-based canvas used for the AI director workflow graph on /create.',
    license: 'MIT',
    risk: 'safe',
    featureFlag: 'NEXT_PUBLIC_ENABLE_REACT_FLOW',
    envKeys: [],
    productSurface: ['create-canvas', 'workflow-editor'],
    userVisibleCapability: '导演工作台画布',
    stars: 24000,
    homepage: 'https://reactflow.dev',
  },
  {
    id: 'comfyui',
    name: 'ComfyUI',
    tier: 'P0',
    category: 'ai',
    description: 'Node-based Stable Diffusion UI for local image generation. Must run as an isolated service — GPL-3.0 code cannot be mixed into this codebase.',
    license: 'GPL-3.0',
    risk: 'service_isolation_required',
    featureFlag: 'NEXT_PUBLIC_ENABLE_COMFYUI',
    envKeys: ['COMFYUI_BASE_URL', 'COMFYUI_API_KEY'],
    productSurface: ['image-generation', 'local-diffusion'],
    userVisibleCapability: '本地 AI 图像生成',
    stars: 65000,
    homepage: 'https://github.com/comfyanonymous/ComfyUI',
    notes: 'GPL-3.0: integrate only via HTTP API from an independent process. Never import ComfyUI Python or copy code into this repo.',
  },

  // ── P1: High-value add-ons ────────────────────────────────────────────────
  {
    id: 'opencut',
    name: 'OpenCut',
    tier: 'P1',
    category: 'media',
    description: 'Open-source video editor for in-browser timeline editing.',
    license: 'MIT',
    risk: 'license_review',
    featureFlag: 'NEXT_PUBLIC_ENABLE_OPENCUT',
    envKeys: [],
    productSurface: ['video-editor', 'timeline'],
    userVisibleCapability: '视频时间线剪辑',
    stars: 18000,
    homepage: 'https://opencut.app',
    notes: 'Verify MIT license scope before integrating — fork-based integration may create attribution obligations.',
  },
  {
    id: 'whisper-asr',
    name: 'OpenAI Whisper',
    tier: 'P1',
    category: 'ai',
    description: 'Speech-to-text transcription for video subtitle generation and voice analysis.',
    license: 'MIT',
    risk: 'safe',
    featureFlag: 'NEXT_PUBLIC_ENABLE_WHISPER',
    envKeys: ['WHISPER_API_URL', 'WHISPER_API_KEY'],
    productSurface: ['video-subtitles', 'voice-transcription'],
    userVisibleCapability: '语音转文字字幕',
    stars: 77000,
    homepage: 'https://github.com/openai/whisper',
  },
  {
    id: 'qdrant',
    name: 'Qdrant',
    tier: 'P1',
    category: 'ai',
    description: 'Vector database for semantic asset search, style retrieval, and shot matching.',
    license: 'Apache-2.0',
    risk: 'safe',
    featureFlag: 'NEXT_PUBLIC_ENABLE_QDRANT',
    envKeys: ['QDRANT_URL', 'QDRANT_API_KEY'],
    productSurface: ['asset-search', 'style-retrieval', 'shot-matching'],
    userVisibleCapability: '语义资产搜索',
    stars: 22000,
    homepage: 'https://qdrant.tech',
  },
  {
    id: 'yjs-hocuspocus',
    name: 'Yjs + Hocuspocus',
    tier: 'P1',
    category: 'collaboration',
    description: 'CRDT-based real-time collaboration for shared canvas and project editing.',
    license: 'MIT',
    risk: 'safe',
    featureFlag: 'NEXT_PUBLIC_ENABLE_COLLABORATION',
    envKeys: ['HOCUSPOCUS_URL', 'HOCUSPOCUS_SECRET'],
    productSurface: ['canvas-collaboration', 'shared-editing'],
    userVisibleCapability: '多人实时协作',
    stars: 18000,
    homepage: 'https://hocuspocus.dev',
  },

  // ── P2: Extended capabilities ─────────────────────────────────────────────
  {
    id: 'livekit',
    name: 'LiveKit',
    tier: 'P2',
    category: 'collaboration',
    description: 'WebRTC infrastructure for live video review sessions and co-production.',
    license: 'Apache-2.0',
    risk: 'license_review',
    featureFlag: 'NEXT_PUBLIC_ENABLE_LIVEKIT',
    envKeys: ['LIVEKIT_API_KEY', 'LIVEKIT_API_SECRET', 'NEXT_PUBLIC_LIVEKIT_URL'],
    productSurface: ['live-review', 'co-production', 'video-room'],
    userVisibleCapability: '实时视频协作间',
    stars: 12000,
    homepage: 'https://livekit.io',
  },
  {
    id: 'pyscenedetect',
    name: 'PySceneDetect',
    tier: 'P2',
    category: 'media',
    description: 'Automatic shot boundary detection for AI-assisted video analysis.',
    license: 'BSD-3-Clause',
    risk: 'safe',
    featureFlag: 'NEXT_PUBLIC_ENABLE_SHOT_DETECTION',
    envKeys: ['SHOT_DETECTION_API_URL'],
    productSurface: ['shot-detection', 'video-analysis'],
    userVisibleCapability: '自动分镜检测',
    stars: 3800,
    homepage: 'https://www.scenedetect.com',
  },
  {
    id: 'mediabunny',
    name: 'Mediabunny',
    tier: 'P2',
    category: 'media',
    description: 'Browser-native media processing (trim, concat, transcode) without server round-trips.',
    license: 'MPL-2.0',
    risk: 'license_review',
    featureFlag: 'NEXT_PUBLIC_ENABLE_BROWSER_MEDIA',
    envKeys: [],
    productSurface: ['browser-transcode', 'client-trim', 'wasm-processing'],
    userVisibleCapability: '浏览器端视频处理',
    stars: 420,
    homepage: 'https://mediabunny.dev',
    notes: 'MPL-2.0: modifications to Mediabunny source must be shared, but application code is not affected.',
  },
  {
    id: 'mcp-servers',
    name: 'MCP Servers',
    tier: 'P2',
    category: 'protocol',
    description: 'Model Context Protocol servers for tool-augmented AI generation and agent integration.',
    license: 'MIT',
    risk: 'safe',
    featureFlag: 'NEXT_PUBLIC_ENABLE_MCP',
    envKeys: ['MCP_SERVER_URL', 'MCP_API_KEY'],
    productSurface: ['agent-tools', 'ai-integration', 'tool-use'],
    userVisibleCapability: 'AI 工具协议集成',
    stars: 9500,
    homepage: 'https://modelcontextprotocol.io',
  },

  // ── Deferred / reference_only ─────────────────────────────────────────────
  {
    id: 'n8n',
    name: 'n8n',
    tier: 'deferred',
    category: 'integration',
    description: 'Workflow automation platform. Deferred due to fair-code license restrictions.',
    license: 'fair-code',
    risk: 'reference_only',
    featureFlag: 'NEXT_PUBLIC_ENABLE_N8N',
    envKeys: ['N8N_URL', 'N8N_API_KEY'],
    productSurface: [],
    userVisibleCapability: '工作流自动化（延期）',
    stars: 52000,
    homepage: 'https://n8n.io',
    notes: 'fair-code: cannot be sold as SaaS without license. Deferred pending commercial license evaluation.',
  },
  {
    id: 'dify',
    name: 'Dify',
    tier: 'deferred',
    category: 'integration',
    description: 'LLM application platform. Deferred — overlapping scope with internal director system.',
    license: 'Apache-2.0',
    risk: 'reference_only',
    featureFlag: 'NEXT_PUBLIC_ENABLE_DIFY',
    envKeys: ['DIFY_API_URL', 'DIFY_API_KEY'],
    productSurface: [],
    userVisibleCapability: 'LLM 应用平台（延期）',
    stars: 56000,
    homepage: 'https://dify.ai',
    notes: 'Deferred: scope conflicts with built-in AI director. Consider only for external workflow orchestration.',
  },
  {
    id: 'tldraw',
    name: 'tldraw',
    tier: 'deferred',
    category: 'canvas',
    description: 'Infinite canvas whiteboard. Deferred — custom tldraw license restricts commercial use.',
    license: 'custom',
    risk: 'reference_only',
    featureFlag: 'NEXT_PUBLIC_ENABLE_TLDRAW',
    envKeys: [],
    productSurface: [],
    userVisibleCapability: '无限白板（延期）',
    stars: 39000,
    homepage: 'https://tldraw.dev',
    notes: 'Custom license: commercial deployment requires explicit approval from tldraw team.',
  },
  {
    id: 'remotion',
    name: 'Remotion',
    tier: 'deferred',
    category: 'media',
    description: 'React-based programmatic video rendering. Deferred — commercial license required.',
    license: 'custom',
    risk: 'reference_only',
    featureFlag: 'NEXT_PUBLIC_ENABLE_REMOTION',
    envKeys: [],
    productSurface: [],
    userVisibleCapability: '程序化视频渲染（延期）',
    stars: 21000,
    homepage: 'https://remotion.dev',
    notes: 'Commercial use requires paid license from Remotion. Deferred pending licensing decision.',
  },
  {
    id: 'minio',
    name: 'MinIO',
    tier: 'deferred',
    category: 'storage',
    description: 'Self-hosted S3-compatible storage. Deferred — AGPL-3.0 requires service-level isolation.',
    license: 'AGPL-3.0',
    risk: 'reference_only',
    featureFlag: 'NEXT_PUBLIC_ENABLE_MINIO',
    envKeys: ['MINIO_ENDPOINT', 'MINIO_ACCESS_KEY', 'MINIO_SECRET_KEY'],
    productSurface: [],
    userVisibleCapability: '自托管对象存储（延期）',
    stars: 49000,
    homepage: 'https://min.io',
    notes: 'AGPL-3.0: self-hosting is fine, offering as a service triggers copyleft. Deferred.',
  },
  {
    id: 'designcombo',
    name: 'DesignCombo',
    tier: 'deferred',
    category: 'media',
    description: 'Open-source video timeline editor component. Deferred pending UI integration planning.',
    license: 'MIT',
    risk: 'reference_only',
    featureFlag: 'NEXT_PUBLIC_ENABLE_DESIGNCOMBO',
    envKeys: [],
    productSurface: [],
    userVisibleCapability: '视频时间线组件（延期）',
    stars: 1400,
    homepage: 'https://designcombo.dev',
    notes: 'Deferred: overlaps with OpenCut. Evaluate after OpenCut integration.',
  },
]

export function getToolById(id: string) {
  return OPEN_SOURCE_TOOL_REGISTRY.find((t) => t.id === id) ?? null
}

export function getToolsByTier(tier: OpenSourceToolDefinition['tier']) {
  return OPEN_SOURCE_TOOL_REGISTRY.filter((t) => t.tier === tier)
}

export function getActiveTools() {
  return OPEN_SOURCE_TOOL_REGISTRY.filter((t) => t.tier !== 'deferred')
}
