import type { NodeToolEntry } from './nodeToolTypes'

export const NODE_TOOL_REGISTRY: readonly NodeToolEntry[] = [
  // ── Category A: 提示词与导演参数 ─────────────────────────────────────────
  {
    id: 'camera-control',
    label: '摄影机控制',
    icon: '🎥',
    description: '设置景别、运镜和焦距',
    category: 'prompt-direction',
    executionType: 'panel',
    supportedKinds: ['image', 'video'],
    requiresMedia: false,
    requiresAsset: false,
    available: true,
    openActionId: 'camera-control',
    outputKind: 'configuration',
    outputLabel: '调整任务参数',
    primaryActionLabel: '应用到任务',
  },
  {
    id: 'camera-lexicon',
    label: '镜头词典',
    icon: '📷',
    description: '浏览摄影机词汇注入提示词',
    category: 'prompt-direction',
    executionType: 'panel',
    supportedKinds: ['image', 'video'],
    requiresMedia: false,
    requiresAsset: false,
    available: true,
    openActionId: 'camera-lexicon',
    outputKind: 'configuration',
    outputLabel: '调整任务参数',
    primaryActionLabel: '应用到任务',
  },
  {
    id: 'scene-lighting',
    label: '场景光线',
    icon: '💡',
    description: '配置场景光照类型',
    category: 'prompt-direction',
    executionType: 'panel',
    supportedKinds: ['image', 'video'],
    requiresMedia: false,
    requiresAsset: false,
    available: true,
    openActionId: 'scene-lighting',
    outputKind: 'configuration',
    outputLabel: '调整任务参数',
    primaryActionLabel: '应用到任务',
  },
  {
    id: 'prompt-booster',
    label: '提示词增强',
    icon: '✨',
    description: 'AI 扩写提示词',
    category: 'prompt-direction',
    executionType: 'panel',
    supportedKinds: ['text', 'image', 'video'],
    requiresMedia: false,
    requiresAsset: false,
    available: true,
    openActionId: 'prompt-booster',
    outputKind: 'configuration',
    outputLabel: '调整任务参数',
    primaryActionLabel: '应用到任务',
  },
  {
    id: 'script-segmentation',
    label: '剧本分场',
    icon: '§',
    description: '将文本拆分为可审核的场景节点',
    category: 'prompt-direction',
    executionType: 'panel',
    supportedKinds: ['text'],
    requiresMedia: false,
    requiresAsset: false,
    available: true,
    openActionId: 'script-segmentation',
    outputKind: 'structured-text',
    outputLabel: '文本节点',
    primaryActionLabel: '创建分场节点',
  },
  {
    id: 'narrative-beat-analysis',
    label: '叙事节拍分析',
    icon: '◆',
    description: '将场景文本拆分为可审核的叙事节拍',
    category: 'prompt-direction',
    executionType: 'panel',
    supportedKinds: ['text'],
    requiresMedia: false,
    requiresAsset: false,
    available: true,
    openActionId: 'narrative-beat-analysis',
    outputKind: 'structured-text',
    outputLabel: '文本节点',
    primaryActionLabel: '创建节拍节点',
  },
  {
    id: 'shot-list-builder',
    label: '分镜清单生成器',
    icon: '◇',
    description: '将文本规划为可审核的分镜清单',
    category: 'prompt-direction',
    executionType: 'panel',
    supportedKinds: ['text'],
    requiresMedia: false,
    requiresAsset: false,
    available: true,
    openActionId: 'shot-list-builder',
    outputKind: 'structured-text',
    outputLabel: '文本节点',
    primaryActionLabel: '创建分镜清单',
  },
  {
    id: 'storyboard-director',
    label: '分镜导演',
    icon: '🎬',
    description: '编排剧本分场、叙事节拍与镜头规划',
    category: 'prompt-direction',
    executionType: 'panel',
    supportedKinds: ['text'],
    requiresMedia: false,
    requiresAsset: false,
    available: true,
    openActionId: 'storyboard-director',
    outputKind: 'structured-text',
    outputLabel: '分镜工作流',
    primaryActionLabel: '打开分镜导演',
  },
  {
    id: 'look-package',
    label: '视觉风格包',
    icon: '🎨',
    description: '选择视觉风格方案注入提示词',
    category: 'prompt-direction',
    executionType: 'panel',
    supportedKinds: ['image', 'video'],
    requiresMedia: false,
    requiresAsset: false,
    available: true,
    openActionId: 'look-package',
    outputKind: 'configuration',
    outputLabel: '调整任务参数',
    primaryActionLabel: '应用到任务',
  },
  {
    id: 'variant-planner',
    label: '资产变体规划',
    icon: '⬡',
    description: '规划不同变体方向',
    category: 'prompt-direction',
    executionType: 'panel',
    supportedKinds: ['image', 'video'],
    requiresMedia: false,
    requiresAsset: false,
    available: true,
    openActionId: 'variant-planner',
    outputKind: 'configuration',
    outputLabel: '调整任务参数',
    primaryActionLabel: '应用到任务',
  },
  // ── Category B: 画面编辑 ─────────────────────────────────────────────────
  {
    id: 'storyboard-reference-extractor',
    label: '分镜参考提取',
    icon: '⌑',
    description: '自由选取画面参考并建立来源关系',
    category: 'image-edit',
    executionType: 'panel',
    supportedKinds: ['image'],
    requiresMedia: true,
    requiresAsset: true,
    available: true,
    openActionId: 'storyboard-reference-extractor',
    outputKind: 'derived-image',
    outputLabel: '图片节点',
    primaryActionLabel: '创建参考图节点',
  },
  {
    id: 'draw-annotation',
    label: '画面标注',
    icon: '✎',
    description: '在图片上保存画笔、箭头、形状和文字标注',
    category: 'image-edit',
    executionType: 'panel',
    supportedKinds: ['image'],
    requiresMedia: true,
    requiresAsset: false,
    available: true,
    openActionId: 'draw-annotation',
    outputKind: 'derived-image',
    outputLabel: '图片标注',
    primaryActionLabel: '保存标注',
  },
  {
    id: 'remove-background',
    label: '主体抠图',
    icon: '✂',
    description: '去除背景，保留主体',
    category: 'image-edit',
    executionType: 'panel',
    supportedKinds: ['image'],
    requiresMedia: true,
    requiresAsset: false,
    capabilityKey: 'removeBackground',
    available: false,
    openActionId: 'remove-background',
    outputKind: 'derived-image',
    outputLabel: '图片节点',
    primaryActionLabel: '创建透明背景图',
    unavailableReason: '主体抠图执行器尚不可用',
  },
  {
    id: 'hd-reconstruction',
    label: '高清重建',
    icon: '⬆',
    description: '超分辨率重建图像',
    category: 'image-edit',
    executionType: 'panel',
    supportedKinds: ['image'],
    requiresMedia: true,
    requiresAsset: false,
    capabilityKey: 'upscale',
    available: false,
    openActionId: 'hd-reconstruction',
    outputKind: 'derived-image',
    outputLabel: '图片节点',
    primaryActionLabel: '创建高清图片',
    unavailableReason: '高清重建执行器尚不可用',
  },
  // ── Category C: 分析与预览 ───────────────────────────────────────────────
  {
    id: 'color-grade',
    label: '调色盘',
    icon: '🎛',
    description: '调整画面色彩和对比度（预览）',
    category: 'analysis-preview',
    executionType: 'preview',
    supportedKinds: ['image', 'video'],
    requiresMedia: true,
    requiresAsset: false,
    available: true,
    openActionId: 'color-grade',
    outputKind: 'preview',
    outputLabel: '预览',
    primaryActionLabel: '打开调色预览',
  },
  {
    id: 'keyframe-extractor',
    label: '关键帧提取',
    icon: '🎞',
    description: '从视频当前时间建立图片或视频续作草稿',
    category: 'analysis-preview',
    executionType: 'panel',
    supportedKinds: ['video'],
    requiresMedia: true,
    requiresAsset: false,
    available: true,
    openActionId: 'keyframe-extractor',
    outputKind: 'analysis',
    outputLabel: '关键帧结果',
    primaryActionLabel: '提取关键帧',
  },
] as const
