import type { NodeToolEntry } from './nodeToolTypes'

export const NODE_TOOL_REGISTRY: readonly NodeToolEntry[] = [
  // ── Category A: 提示词与导演参数 ─────────────────────────────────────────
  {
    id: 'camera-control',
    label: '摄影机控制',
    icon: '🎥',
    description: '设置景别、运镜和焦距',
    category: 'prompt-direction',
    executionType: 'panel',
    supportedKinds: ['image', 'video'],
    requiresMedia: false,
    requiresAsset: false,
    available: true,
    openActionId: 'camera-control',
  },
  {
    id: 'camera-lexicon',
    label: '镜头词典',
    icon: '📷',
    description: '浏览摄影机词汇注入提示词',
    category: 'prompt-direction',
    executionType: 'panel',
    supportedKinds: ['image', 'video'],
    requiresMedia: false,
    requiresAsset: false,
    available: true,
    openActionId: 'camera-lexicon',
  },
  {
    id: 'scene-lighting',
    label: '场景光线',
    icon: '💡',
    description: '配置场景光照类型',
    category: 'prompt-direction',
    executionType: 'panel',
    supportedKinds: ['image', 'video'],
    requiresMedia: false,
    requiresAsset: false,
    available: true,
    openActionId: 'scene-lighting',
  },
  {
    id: 'prompt-booster',
    label: '提示词增强',
    icon: '✨',
    description: 'AI 扩写提示词',
    category: 'prompt-direction',
    executionType: 'panel',
    supportedKinds: ['text', 'image', 'video'],
    requiresMedia: false,
    requiresAsset: false,
    available: true,
    openActionId: 'prompt-booster',
  },
  {
    id: 'script-segmentation',
    label: '剧本分场',
    icon: '§',
    description: '将文本拆分为可审核的场景节点',
    category: 'prompt-direction',
    executionType: 'panel',
    supportedKinds: ['text'],
    requiresMedia: false,
    requiresAsset: false,
    available: true,
    openActionId: 'script-segmentation',
  },
  {
    id: 'narrative-beat-analysis',
    label: '叙事节拍分析',
    icon: '◆',
    description: '将场景文本拆分为可审核的叙事节拍',
    category: 'prompt-direction',
    executionType: 'panel',
    supportedKinds: ['text'],
    requiresMedia: false,
    requiresAsset: false,
    available: true,
    openActionId: 'narrative-beat-analysis',
  },
  {
    id: 'shot-list-builder',
    label: '分镜清单生成器',
    icon: '◇',
    description: '将文本规划为可审核的分镜清单',
    category: 'prompt-direction',
    executionType: 'panel',
    supportedKinds: ['text'],
    requiresMedia: false,
    requiresAsset: false,
    available: true,
    openActionId: 'shot-list-builder',
  },
  {
    id: 'look-package',
    label: '视觉风格包',
    icon: '🎨',
    description: '选择视觉风格方案注入提示词',
    category: 'prompt-direction',
    executionType: 'panel',
    supportedKinds: ['image', 'video'],
    requiresMedia: false,
    requiresAsset: false,
    available: true,
    openActionId: 'look-package',
  },
  {
    id: 'variant-planner',
    label: '资产变体规划',
    icon: '⬡',
    description: '规划不同变体方向',
    category: 'prompt-direction',
    executionType: 'panel',
    supportedKinds: ['image', 'video'],
    requiresMedia: false,
    requiresAsset: false,
    available: true,
    openActionId: 'variant-planner',
  },
  // ── Category B: 画面编辑 ─────────────────────────────────────────────────
  {
    id: 'storyboard-grid-split',
    label: '分镜拆格',
    icon: '▦',
    description: '识别分镜网格并裁切为独立资产',
    category: 'image-edit',
    executionType: 'panel',
    supportedKinds: ['image'],
    requiresMedia: true,
    requiresAsset: true,
    available: true,
    openActionId: 'storyboard-grid-split',
  },
  {
    id: 'draw-annotation',
    label: '画面标注',
    icon: '✎',
    description: '在图片上保存画笔、箭头、形状和文字标注',
    category: 'image-edit',
    executionType: 'panel',
    supportedKinds: ['image'],
    requiresMedia: true,
    requiresAsset: false,
    available: true,
    openActionId: 'draw-annotation',
  },
  {
    id: 'remove-background',
    label: '主体抠图',
    icon: '✂',
    description: '去除背景，保留主体',
    category: 'image-edit',
    executionType: 'panel',
    supportedKinds: ['image'],
    requiresMedia: true,
    requiresAsset: false,
    capabilityKey: 'removeBackground',
    available: false,
    openActionId: 'remove-background',
  },
  {
    id: 'hd-reconstruction',
    label: '高清重建',
    icon: '⬆',
    description: '超分辨率重建图像',
    category: 'image-edit',
    executionType: 'panel',
    supportedKinds: ['image'],
    requiresMedia: true,
    requiresAsset: false,
    capabilityKey: 'upscale',
    available: false,
    openActionId: 'hd-reconstruction',
  },
  // ── Category C: 分析与预览 ───────────────────────────────────────────────
  {
    id: 'color-grade',
    label: '调色盘',
    icon: '🎛',
    description: '调整画面色彩和对比度（预览）',
    category: 'analysis-preview',
    executionType: 'preview',
    supportedKinds: ['image', 'video'],
    requiresMedia: true,
    requiresAsset: false,
    available: true,
    openActionId: 'color-grade',
  },
] as const
