import type { NodeToolEntry } from './nodeToolTypes'

export const NODE_TOOL_REGISTRY: readonly NodeToolEntry[] = [
  // ── Category A: 提示词与导演参数 ─────────────────────────────────────────
  {
    id: 'camera-control',
    label: '摄影机控制',
    icon: '🎥',
    description: '设置景别、运镜和焦距',
    category: 'prompt-direction',
    executionType: 'panel',
    supportedKinds: ['image', 'video'],
    requiresMedia: false,
    requiresAsset: false,
    available: true,
    openActionId: 'camera-control',
  },
  {
    id: 'camera-lexicon',
    label: '镜头词典',
    icon: '📷',
    description: '浏览摄影机词汇注入提示词',
    category: 'prompt-direction',
    executionType: 'panel',
    supportedKinds: ['image', 'video'],
    requiresMedia: false,
    requiresAsset: false,
    available: true,
    openActionId: 'camera-lexicon',
  },
  {
    id: 'scene-lighting',
    label: '场景光线',
    icon: '💡',
    description: '配置场景光照类型',
    category: 'prompt-direction',
    executionType: 'panel',
    supportedKinds: ['image', 'video'],
    requiresMedia: false,
    requiresAsset: false,
    available: true,
    openActionId: 'scene-lighting',
  },
  {
    id: 'prompt-booster',
    label: '提示词增强',
    icon: '✨',
    description: 'AI 扩写提示词',
    category: 'prompt-direction',
    executionType: 'panel',
    supportedKinds: ['text', 'image', 'video'],
    requiresMedia: false,
    requiresAsset: false,
    available: true,
    openActionId: 'prompt-booster',
  },
  {
    id: 'look-package',
    label: '视觉风格包',
    icon: '🎨',
    description: '选择视觉风格方案注入提示词',
    category: 'prompt-direction',
    executionType: 'panel',
    supportedKinds: ['image', 'video'],
    requiresMedia: false,
    requiresAsset: false,
    available: true,
    openActionId: 'look-package',
  },
  {
    id: 'variant-planner',
    label: '资产变体规划',
    icon: '⬡',
    description: '规划不同变体方向',
    category: 'prompt-direction',
    executionType: 'panel',
    supportedKinds: ['image', 'video'],
    requiresMedia: false,
    requiresAsset: false,
    available: true,
    openActionId: 'variant-planner',
  },
  // ── Category B: 画面编辑 ─────────────────────────────────────────────────
  {
    id: 'remove-background',
    label: '主体抠图',
    icon: '✂',
    description: '去除背景，保留主体',
    category: 'image-edit',
    executionType: 'panel',
    supportedKinds: ['image'],
    requiresMedia: true,
    requiresAsset: false,
    capabilityKey: 'removeBackground',
    available: false,
    openActionId: 'remove-background',
  },
  {
    id: 'hd-reconstruction',
    label: '高清重建',
    icon: '⬆',
    description: '超分辨率重建图像',
    category: 'image-edit',
    executionType: 'panel',
    supportedKinds: ['image'],
    requiresMedia: true,
    requiresAsset: false,
    capabilityKey: 'upscale',
    available: false,
    openActionId: 'hd-reconstruction',
  },
  // ── Category C: 分析与预览 ───────────────────────────────────────────────
  {
    id: 'color-grade',
    label: '调色盘',
    icon: '🎛',
    description: '调整画面色彩和对比度（预览）',
    category: 'analysis-preview',
    executionType: 'preview',
    supportedKinds: ['image', 'video'],
    requiresMedia: true,
    requiresAsset: false,
    available: true,
    openActionId: 'color-grade',
  },
] as const
